use std::io;

use chrono::{DateTime, Utc};

use super::{ComplianceGap, ComplianceStatus, EvidencePackage, GapSeverity, IntegrityState};

const PDF_TITLE: &str = "TRAILING AUDIT EVIDENCE REPORT";
const PAGE_WIDTH: f32 = 612.0;
const PAGE_HEIGHT: f32 = 792.0;
const LEFT_MARGIN: f32 = 48.0;
const RIGHT_MARGIN: f32 = 48.0;
const TOP_MARGIN: f32 = 52.0;
const BOTTOM_MARGIN: f32 = 40.0;
const FOOTER_RESERVED: f32 = 28.0;
const CONTENT_WIDTH: f32 = PAGE_WIDTH - LEFT_MARGIN - RIGHT_MARGIN;
const CONTENT_BOTTOM: f32 = PAGE_HEIGHT - BOTTOM_MARGIN - FOOTER_RESERVED;
const BODY_LINE_HEIGHT: f32 = 14.0;
const TABLE_FONT_SIZE: f32 = 9.0;
const TABLE_LINE_HEIGHT: f32 = 12.0;
const SECTION_HEADER_HEIGHT: f32 = 24.0;
const CELL_PADDING_X: f32 = 6.0;
const CELL_PADDING_Y: f32 = 5.0;

pub fn export_package(package: &EvidencePackage) -> io::Result<Vec<u8>> {
    let mut normalized = package.clone();
    normalized.refresh_hash();

    let report = Report::from_package(&normalized);
    render_pdf(&report)
}

struct Report {
    title_page: TitlePage,
    sections: Vec<ReportSection>,
}

impl Report {
    fn from_package(package: &EvidencePackage) -> Self {
        let (range_start, range_end) = package_time_range(package)
            .unwrap_or((package.metadata.generated_at, package.metadata.generated_at));
        let time_range = format_time_range(range_start, range_end);
        let controls_met = package
            .compliance_report
            .controls
            .iter()
            .filter(|control| control.status == ComplianceStatus::Compliant)
            .count();
        let frameworks = usize::from(!package.compliance_report.framework.trim().is_empty());
        let proofs_verified = package
            .chain_integrity_status
            .proofs
            .iter()
            .filter(|proof| proof.verified)
            .count();

        let summary = ReportSection {
            title: "Summary Statistics".to_string(),
            elements: vec![SectionElement::Summary(SummarySection {
                cards: vec![
                    MetricCard {
                        label: "Total Actions".to_string(),
                        value: package.actions.len().to_string(),
                    },
                    MetricCard {
                        label: "Frameworks".to_string(),
                        value: frameworks.to_string(),
                    },
                    MetricCard {
                        label: "Oversight Events".to_string(),
                        value: package.oversight_events.len().to_string(),
                    },
                ],
                time_range: time_range.clone(),
                detail_table: TableSpec {
                    caption: Some("Report Overview".to_string()),
                    columns: vec![
                        TableColumn::new("Field", 148.0),
                        TableColumn::new("Value", CONTENT_WIDTH - 148.0),
                    ],
                    rows: vec![
                        vec!["Package ID".to_string(), package.metadata.package_id.clone()],
                        vec!["Subject".to_string(), package.metadata.subject.clone()],
                        vec!["Organization".to_string(), package.metadata.organization.clone()],
                        vec!["Generated By".to_string(), package.metadata.generated_by.clone()],
                        vec![
                            "Generated At".to_string(),
                            format_timestamp(package.metadata.generated_at),
                        ],
                        vec![
                            "Framework".to_string(),
                            package.compliance_report.framework.clone(),
                        ],
                        vec![
                            "Overall Status".to_string(),
                            status_label(&package.compliance_report.status).to_string(),
                        ],
                        vec!["Package Hash".to_string(), package.package_hash.clone()],
                    ],
                },
            })],
        };

        let chain_integrity = ReportSection {
            title: "Chain Integrity".to_string(),
            elements: vec![SectionElement::Table(TableSpec {
                caption: None,
                columns: vec![
                    TableColumn::new("Metric", 148.0),
                    TableColumn::new("Value", CONTENT_WIDTH - 148.0),
                ],
                rows: vec![
                    vec![
                        "Status".to_string(),
                        integrity_label(&package.chain_integrity_status.status).to_string(),
                    ],
                    vec![
                        "Entries Checked".to_string(),
                        (package.actions.len() + package.oversight_events.len()).to_string(),
                    ],
                    vec![
                        "Verified Proofs".to_string(),
                        format!(
                            "{proofs_verified} / {}",
                            package.chain_integrity_status.proofs.len()
                        ),
                    ],
                    vec![
                        "Broken Links".to_string(),
                        package.chain_integrity_status.broken_links.to_string(),
                    ],
                    vec![
                        "Last Verified At".to_string(),
                        format_timestamp(package.chain_integrity_status.last_verified_at),
                    ],
                    vec![
                        "Latest Root Hash".to_string(),
                        package.chain_integrity_status.ledger_root_hash.clone(),
                    ],
                ],
            })],
        };

        let actions = ReportSection {
            title: "Action Timeline".to_string(),
            elements: vec![SectionElement::Table(TableSpec {
                caption: None,
                columns: vec![
                    TableColumn::new("Action ID", 68.0),
                    TableColumn::new("Timestamp", 96.0),
                    TableColumn::new("Agent", 64.0),
                    TableColumn::new("Type", 58.0),
                    TableColumn::new("Session", 64.0),
                    TableColumn::new("Summary", CONTENT_WIDTH - 350.0),
                ],
                rows: rows_or_placeholder(
                    package
                        .actions
                        .iter()
                        .map(|action| {
                            vec![
                                action.action_id.clone(),
                                format_timestamp(action.timestamp),
                                action.agent_id.clone(),
                                action.action_type.clone(),
                                action.session_id.clone(),
                                action.summary.clone(),
                            ]
                        })
                        .collect(),
                    6,
                    "No actions recorded.",
                ),
            })],
        };

        let oversight = ReportSection {
            title: "Oversight Log".to_string(),
            elements: vec![SectionElement::Table(TableSpec {
                caption: None,
                columns: vec![
                    TableColumn::new("Event ID", 64.0),
                    TableColumn::new("Timestamp", 96.0),
                    TableColumn::new("Reviewer", 72.0),
                    TableColumn::new("Type", 60.0),
                    TableColumn::new("Disposition", 70.0),
                    TableColumn::new("Details", CONTENT_WIDTH - 362.0),
                ],
                rows: rows_or_placeholder(
                    package
                        .oversight_events
                        .iter()
                        .map(|event| {
                            vec![
                                event.event_id.clone(),
                                format_timestamp(event.timestamp),
                                event.reviewer.clone(),
                                event.event_type.clone(),
                                event.disposition.clone(),
                                event.details.clone(),
                            ]
                        })
                        .collect(),
                    6,
                    "No oversight events recorded.",
                ),
            })],
        };

        let compliance = ReportSection {
            title: "Compliance Matrix".to_string(),
            elements: vec![
                SectionElement::Table(TableSpec {
                    caption: Some("Compliance Summary".to_string()),
                    columns: vec![
                        TableColumn::new("Metric", 148.0),
                        TableColumn::new("Value", CONTENT_WIDTH - 148.0),
                    ],
                    rows: vec![
                        vec![
                            "Framework".to_string(),
                            package.compliance_report.framework.clone(),
                        ],
                        vec![
                            "Overall Status".to_string(),
                            status_label(&package.compliance_report.status).to_string(),
                        ],
                        vec![
                            "Controls Met".to_string(),
                            format!(
                                "{controls_met} / {}",
                                package.compliance_report.controls.len()
                            ),
                        ],
                        vec![
                            "Gap Count".to_string(),
                            package.compliance_report.gaps.len().to_string(),
                        ],
                    ],
                }),
                SectionElement::Table(TableSpec {
                    caption: Some("Controls".to_string()),
                    columns: vec![
                        TableColumn::new("Control", 66.0),
                        TableColumn::new("Title", 160.0),
                        TableColumn::new("Status", 66.0),
                        TableColumn::new("Evidence", 112.0),
                        TableColumn::new("Notes", CONTENT_WIDTH - 404.0),
                    ],
                    rows: rows_or_placeholder(
                        package
                            .compliance_report
                            .controls
                            .iter()
                            .map(|control| {
                                vec![
                                    control.control_id.clone(),
                                    control.title.clone(),
                                    status_label(&control.status).to_string(),
                                    join_or_dash(&control.evidence_refs),
                                    control.notes.clone().unwrap_or_else(|| "-".to_string()),
                                ]
                            })
                            .collect(),
                        5,
                        "No compliance controls recorded.",
                    ),
                }),
            ],
        };

        let gaps = ReportSection {
            title: "Gaps".to_string(),
            elements: vec![SectionElement::Table(TableSpec {
                caption: None,
                columns: vec![
                    TableColumn::new("Gap ID", 62.0),
                    TableColumn::new("Severity", 64.0),
                    TableColumn::new("Owner", 112.0),
                    TableColumn::new("Description", CONTENT_WIDTH - 238.0),
                ],
                rows: gap_rows(&package.compliance_report.gaps),
            })],
        };

        Self {
            title_page: TitlePage {
                framework: package.compliance_report.framework.clone(),
                date_range: time_range,
                generated_at: format_timestamp(package.metadata.generated_at),
                subject: package.metadata.subject.clone(),
                organization: package.metadata.organization.clone(),
                package_id: package.metadata.package_id.clone(),
            },
            sections: vec![summary, chain_integrity, actions, oversight, compliance, gaps],
        }
    }
}

struct TitlePage {
    framework: String,
    date_range: String,
    generated_at: String,
    subject: String,
    organization: String,
    package_id: String,
}

struct ReportSection {
    title: String,
    elements: Vec<SectionElement>,
}

enum SectionElement {
    Summary(SummarySection),
    Table(TableSpec),
}

struct SummarySection {
    cards: Vec<MetricCard>,
    time_range: String,
    detail_table: TableSpec,
}

struct MetricCard {
    label: String,
    value: String,
}

struct TableSpec {
    caption: Option<String>,
    columns: Vec<TableColumn>,
    rows: Vec<Vec<String>>,
}

struct TableColumn {
    title: String,
    width: f32,
}

impl TableColumn {
    fn new(title: &str, width: f32) -> Self {
        Self {
            title: title.to_string(),
            width,
        }
    }
}

struct PdfPage {
    content: String,
}

impl PdfPage {
    fn new() -> Self {
        Self {
            content: String::new(),
        }
    }
}

#[derive(Clone, Copy)]
enum FontFace {
    Regular,
    Bold,
}

impl FontFace {
    fn resource_name(self) -> &'static str {
        match self {
            Self::Regular => "F1",
            Self::Bold => "F2",
        }
    }

    fn width_factor(self) -> f32 {
        match self {
            Self::Regular => 0.52,
            Self::Bold => 0.56,
        }
    }
}

struct LayoutEngine {
    pages: Vec<PdfPage>,
    current_page: usize,
    cursor_y: f32,
}

impl LayoutEngine {
    fn new() -> Self {
        let mut engine = Self {
            pages: Vec::new(),
            current_page: 0,
            cursor_y: TOP_MARGIN,
        };
        engine.start_new_page();
        engine
    }

    fn start_new_page(&mut self) {
        self.pages.push(PdfPage::new());
        self.current_page = self.pages.len() - 1;
        self.cursor_y = TOP_MARGIN;
    }

    fn current_page_number(&self) -> usize {
        self.current_page + 1
    }

    fn current_page_mut(&mut self) -> &mut PdfPage {
        &mut self.pages[self.current_page]
    }

    fn ensure_space(&mut self, height: f32) {
        if self.cursor_y + height > CONTENT_BOTTOM {
            self.start_new_page();
        }
    }

    fn render_section(&mut self, section: &ReportSection) {
        self.ensure_space(SECTION_HEADER_HEIGHT + 16.0);
        self.render_section_header(&section.title);

        for element in &section.elements {
            match element {
                SectionElement::Summary(summary) => self.render_summary(summary),
                SectionElement::Table(table) => self.render_table(table),
            }
        }

        self.cursor_y += 10.0;
    }

    fn render_section_header(&mut self, title: &str) {
        let top = self.cursor_y;
        append_fill_rect(
            &mut self.current_page_mut().content,
            LEFT_MARGIN,
            top,
            CONTENT_WIDTH,
            SECTION_HEADER_HEIGHT,
            0.18,
        );
        append_text(
            &mut self.current_page_mut().content,
            LEFT_MARGIN + 12.0,
            top + 4.0,
            FontFace::Bold,
            13.0,
            1.0,
            title,
        );
        self.cursor_y += SECTION_HEADER_HEIGHT + 12.0;
    }

    fn render_summary(&mut self, summary: &SummarySection) {
        let gap = 12.0;
        let card_width = (CONTENT_WIDTH - gap * 2.0) / 3.0;
        let card_height = 56.0;
        let cards_top = self.cursor_y;

        self.ensure_space(card_height + 68.0);

        for (index, card) in summary.cards.iter().enumerate() {
            let x = LEFT_MARGIN + (card_width + gap) * index as f32;
            append_fill_rect(
                &mut self.current_page_mut().content,
                x,
                cards_top,
                card_width,
                card_height,
                0.94,
            );
            append_stroke_rect(
                &mut self.current_page_mut().content,
                x,
                cards_top,
                card_width,
                card_height,
                0.80,
                0.8,
            );
            append_text(
                &mut self.current_page_mut().content,
                x + 12.0,
                cards_top + 10.0,
                FontFace::Bold,
                9.0,
                0.35,
                &card.label,
            );
            append_text(
                &mut self.current_page_mut().content,
                x + 12.0,
                cards_top + 26.0,
                FontFace::Bold,
                18.0,
                0.12,
                &card.value,
            );
        }

        self.cursor_y += card_height + 14.0;

        let range_top = self.cursor_y;
        let range_height = 42.0;
        append_fill_rect(
            &mut self.current_page_mut().content,
            LEFT_MARGIN,
            range_top,
            CONTENT_WIDTH,
            range_height,
            0.97,
        );
        append_stroke_rect(
            &mut self.current_page_mut().content,
            LEFT_MARGIN,
            range_top,
            CONTENT_WIDTH,
            range_height,
            0.82,
            0.8,
        );
        append_text(
            &mut self.current_page_mut().content,
            LEFT_MARGIN + 12.0,
            range_top + 8.0,
            FontFace::Bold,
            9.0,
            0.35,
            "Time Range",
        );
        append_text(
            &mut self.current_page_mut().content,
            LEFT_MARGIN + 12.0,
            range_top + 20.0,
            FontFace::Regular,
            11.0,
            0.15,
            &summary.time_range,
        );
        self.cursor_y += range_height + 16.0;

        self.render_table(&summary.detail_table);
    }

    fn render_table(&mut self, table: &TableSpec) {
        if let Some(caption) = &table.caption {
            self.ensure_space(22.0);
            let top = self.cursor_y;
            append_text(
                &mut self.current_page_mut().content,
                LEFT_MARGIN,
                top,
                FontFace::Bold,
                11.0,
                0.18,
                caption,
            );
            self.cursor_y += 18.0;
        }

        let header_values = table
            .columns
            .iter()
            .map(|column| column.title.clone())
            .collect::<Vec<_>>();
        let header_height = table_row_height(&header_values, &table.columns, FontFace::Bold);
        let mut needs_header = true;

        for (row_index, row) in table.rows.iter().enumerate() {
            let row_height = table_row_height(row, &table.columns, FontFace::Regular);
            let needed = if needs_header {
                header_height + row_height
            } else {
                row_height
            };

            if self.cursor_y + needed > CONTENT_BOTTOM {
                self.start_new_page();
                needs_header = true;
            }

            if needs_header {
                let top = self.cursor_y;
                self.draw_table_row(top, table, &header_values, header_height, true, 0);
                self.cursor_y += header_height;
                needs_header = false;
            }

            let top = self.cursor_y;
            self.draw_table_row(top, table, row, row_height, false, row_index);
            self.cursor_y += row_height;
        }

        self.cursor_y += 12.0;
    }

    fn draw_table_row(
        &mut self,
        top: f32,
        table: &TableSpec,
        values: &[String],
        row_height: f32,
        is_header: bool,
        row_index: usize,
    ) {
        let fill_gray = if is_header {
            0.84
        } else if row_index.is_multiple_of(2) {
            0.96
        } else {
            1.0
        };
        append_fill_rect(
            &mut self.current_page_mut().content,
            LEFT_MARGIN,
            top,
            CONTENT_WIDTH,
            row_height,
            fill_gray,
        );
        append_stroke_rect(
            &mut self.current_page_mut().content,
            LEFT_MARGIN,
            top,
            CONTENT_WIDTH,
            row_height,
            0.80,
            0.7,
        );

        let mut x = LEFT_MARGIN;
        for (index, column) in table.columns.iter().enumerate() {
            if index > 0 {
                append_stroke_line(
                    &mut self.current_page_mut().content,
                    x,
                    top,
                    x,
                    top + row_height,
                    0.82,
                    0.6,
                );
            }

            let cell_value = values.get(index).map_or("", String::as_str);
            let lines = wrap_for_width(
                cell_value,
                column.width - CELL_PADDING_X * 2.0,
                if is_header {
                    FontFace::Bold
                } else {
                    FontFace::Regular
                },
                TABLE_FONT_SIZE,
            );

            for (line_index, line) in lines.iter().enumerate() {
                append_text(
                    &mut self.current_page_mut().content,
                    x + CELL_PADDING_X,
                    top + CELL_PADDING_Y + line_index as f32 * TABLE_LINE_HEIGHT,
                    if is_header {
                        FontFace::Bold
                    } else {
                        FontFace::Regular
                    },
                    TABLE_FONT_SIZE,
                    if is_header { 0.14 } else { 0.18 },
                    line,
                );
            }

            x += column.width;
        }
    }
}

fn render_pdf(report: &Report) -> io::Result<Vec<u8>> {
    let mut layout = LayoutEngine::new();
    render_title_page(report, &mut layout.pages[0].content);

    layout.start_new_page();
    let toc_page_index = layout.current_page;
    layout.start_new_page();

    let mut toc_entries = Vec::with_capacity(report.sections.len());
    for section in &report.sections {
        toc_entries.push((section.title.clone(), layout.current_page_number()));
        layout.render_section(section);
    }

    render_toc_page(&mut layout.pages[toc_page_index].content, &toc_entries);

    let page_count = layout.pages.len().max(1);
    for (index, page) in layout.pages.iter_mut().enumerate() {
        append_footer(&mut page.content, index + 1, page_count);
    }

    let catalog_id = 1usize;
    let pages_id = 2usize;
    let regular_font_id = 3usize;
    let bold_font_id = 4usize;
    let info_id = 5usize;
    let mut next_id = 6usize;

    let mut page_ids = Vec::with_capacity(page_count);
    let mut content_ids = Vec::with_capacity(page_count);

    for _ in 0..page_count {
        page_ids.push(next_id);
        next_id += 1;
        content_ids.push(next_id);
        next_id += 1;
    }

    let mut objects = Vec::new();
    objects.push(object(
        catalog_id,
        format!("<< /Type /Catalog /Pages {pages_id} 0 R >>"),
    ));

    let kids = page_ids
        .iter()
        .map(|page_id| format!("{page_id} 0 R"))
        .collect::<Vec<_>>()
        .join(" ");
    objects.push(object(
        pages_id,
        format!("<< /Type /Pages /Kids [{kids}] /Count {page_count} >>"),
    ));
    objects.push(object(
        regular_font_id,
        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>".to_string(),
    ));
    objects.push(object(
        bold_font_id,
        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>".to_string(),
    ));
    objects.push(object(
        info_id,
        format!("<< /Title ({}) /Producer (trailing) >>", escape_text(PDF_TITLE)),
    ));

    for (index, page_id) in page_ids.iter().enumerate() {
        let content_id = content_ids[index];
        objects.push(object(
            *page_id,
            format!(
                "<< /Type /Page /Parent {pages_id} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 {regular_font_id} 0 R /F2 {bold_font_id} 0 R >> >> /Contents {content_id} 0 R >>"
            ),
        ));
        objects.push(stream_object(content_id, &layout.pages[index].content));
    }

    let mut pdf = Vec::new();
    pdf.extend_from_slice(b"%PDF-1.4\n%\xC7\xEC\x8F\xA2\n");

    let mut offsets = Vec::with_capacity(objects.len() + 1);
    offsets.push(0usize);

    for object in &objects {
        offsets.push(pdf.len());
        pdf.extend_from_slice(object.as_bytes());
    }

    let xref_start = pdf.len();
    let object_count = objects.len() + 1;
    pdf.extend_from_slice(format!("xref\n0 {object_count}\n").as_bytes());
    pdf.extend_from_slice(b"0000000000 65535 f \n");

    for offset in offsets.iter().skip(1) {
        pdf.extend_from_slice(format!("{offset:010} 00000 n \n").as_bytes());
    }

    pdf.extend_from_slice(
        format!(
            "trailer\n<< /Size {object_count} /Root {catalog_id} 0 R /Info {info_id} 0 R >>\nstartxref\n{xref_start}\n%%EOF\n"
        )
        .as_bytes(),
    );

    Ok(pdf)
}

fn render_title_page(report: &Report, content: &mut String) {
    append_fill_rect(content, 0.0, 0.0, PAGE_WIDTH, 188.0, 0.18);
    append_fill_rect(content, 0.0, 188.0, PAGE_WIDTH, 8.0, 0.72);

    append_text_centered(content, PAGE_WIDTH / 2.0, 68.0, FontFace::Bold, 24.0, 1.0, PDF_TITLE);
    append_text_centered(
        content,
        PAGE_WIDTH / 2.0,
        108.0,
        FontFace::Regular,
        12.0,
        0.92,
        "Prepared for audit, compliance, and oversight review.",
    );
    append_text_centered(
        content,
        PAGE_WIDTH / 2.0,
        136.0,
        FontFace::Bold,
        14.0,
        1.0,
        &report.title_page.framework,
    );

    let panel_top = 230.0;
    let panel_height = 208.0;
    append_fill_rect(
        content,
        LEFT_MARGIN,
        panel_top,
        CONTENT_WIDTH,
        panel_height,
        0.96,
    );
    append_stroke_rect(
        content,
        LEFT_MARGIN,
        panel_top,
        CONTENT_WIDTH,
        panel_height,
        0.82,
        0.9,
    );
    append_text(
        content,
        LEFT_MARGIN + 16.0,
        panel_top + 14.0,
        FontFace::Bold,
        12.0,
        0.18,
        "Report Details",
    );

    let details = [
        ("Framework", report.title_page.framework.as_str()),
        ("Date Range", report.title_page.date_range.as_str()),
        ("Generated At", report.title_page.generated_at.as_str()),
        ("Subject", report.title_page.subject.as_str()),
        ("Organization", report.title_page.organization.as_str()),
        ("Package ID", report.title_page.package_id.as_str()),
    ];

    let label_x = LEFT_MARGIN + 16.0;
    let value_x = LEFT_MARGIN + 156.0;
    let mut top = panel_top + 42.0;
    for (label, value) in details {
        append_text(content, label_x, top, FontFace::Bold, 10.0, 0.30, label);
        let lines = wrap_for_width(value, CONTENT_WIDTH - 172.0, FontFace::Regular, 11.0);
        for line in &lines {
            append_text(content, value_x, top, FontFace::Regular, 11.0, 0.15, line);
            top += BODY_LINE_HEIGHT;
        }
        top += 8.0;
    }

    append_text_centered(
        content,
        PAGE_WIDTH / 2.0,
        516.0,
        FontFace::Regular,
        11.0,
        0.30,
        "This export preserves the underlying evidence chain while presenting a review-ready report.",
    );
}

fn render_toc_page(content: &mut String, entries: &[(String, usize)]) {
    append_fill_rect(content, 0.0, 0.0, PAGE_WIDTH, 96.0, 0.94);
    append_text(
        content,
        LEFT_MARGIN,
        36.0,
        FontFace::Bold,
        22.0,
        0.18,
        "Table of Contents",
    );
    append_text(
        content,
        LEFT_MARGIN,
        66.0,
        FontFace::Regular,
        10.0,
        0.35,
        "Section headers and page references for this evidence report.",
    );

    let mut top = 132.0;
    for (index, (title, page_number)) in entries.iter().enumerate() {
        let fill = if index % 2 == 0 { 0.97 } else { 1.0 };
        append_fill_rect(content, LEFT_MARGIN, top, CONTENT_WIDTH, 28.0, fill);
        append_stroke_rect(content, LEFT_MARGIN, top, CONTENT_WIDTH, 28.0, 0.85, 0.6);
        append_text(
            content,
            LEFT_MARGIN + 12.0,
            top + 8.0,
            FontFace::Regular,
            11.0,
            0.15,
            title,
        );
        append_text_right_aligned(
            content,
            PAGE_WIDTH - RIGHT_MARGIN - 12.0,
            top + 8.0,
            FontFace::Bold,
            11.0,
            0.18,
            &page_number.to_string(),
        );
        top += 36.0;
    }
}

fn append_footer(content: &mut String, page_number: usize, page_count: usize) {
    append_stroke_line(
        content,
        LEFT_MARGIN,
        PAGE_HEIGHT - 36.0,
        PAGE_WIDTH - RIGHT_MARGIN,
        PAGE_HEIGHT - 36.0,
        0.82,
        0.6,
    );
    append_text_centered(
        content,
        PAGE_WIDTH / 2.0,
        PAGE_HEIGHT - 30.0,
        FontFace::Regular,
        9.0,
        0.35,
        &format!("Page {page_number} of {page_count}"),
    );
}

fn table_row_height(values: &[String], columns: &[TableColumn], font: FontFace) -> f32 {
    let max_lines = columns
        .iter()
        .enumerate()
        .map(|(index, column)| {
            wrap_for_width(
                values.get(index).map_or("", String::as_str),
                column.width - CELL_PADDING_X * 2.0,
                font,
                TABLE_FONT_SIZE,
            )
            .len()
        })
        .max()
        .unwrap_or(1)
        .max(1);

    CELL_PADDING_Y * 2.0 + max_lines as f32 * TABLE_LINE_HEIGHT
}

fn rows_or_placeholder(rows: Vec<Vec<String>>, width: usize, message: &str) -> Vec<Vec<String>> {
    if !rows.is_empty() {
        return rows;
    }

    let mut placeholder = vec![String::new(); width];
    placeholder[0] = message.to_string();
    vec![placeholder]
}

fn gap_rows(gaps: &[ComplianceGap]) -> Vec<Vec<String>> {
    if gaps.is_empty() {
        return rows_or_placeholder(Vec::new(), 4, "No gaps identified.");
    }

    gaps.iter()
        .map(|gap| {
            vec![
                gap.gap_id.clone(),
                severity_label(&gap.severity).to_string(),
                gap.remediation_owner
                    .clone()
                    .unwrap_or_else(|| "unassigned".to_string()),
                gap.description.clone(),
            ]
        })
        .collect()
}

fn join_or_dash(values: &[String]) -> String {
    if values.is_empty() {
        "-".to_string()
    } else {
        values.join(", ")
    }
}

fn package_time_range(package: &EvidencePackage) -> Option<(DateTime<Utc>, DateTime<Utc>)> {
    let mut timestamps = package
        .actions
        .iter()
        .map(|action| action.timestamp)
        .chain(package.oversight_events.iter().map(|event| event.timestamp));
    let first = timestamps.next()?;

    let mut min_timestamp = first;
    let mut max_timestamp = first;

    for timestamp in timestamps {
        if timestamp < min_timestamp {
            min_timestamp = timestamp;
        }
        if timestamp > max_timestamp {
            max_timestamp = timestamp;
        }
    }

    Some((min_timestamp, max_timestamp))
}

fn format_timestamp(timestamp: DateTime<Utc>) -> String {
    timestamp.format("%Y-%m-%d %H:%M:%S UTC").to_string()
}

fn format_time_range(start: DateTime<Utc>, end: DateTime<Utc>) -> String {
    if start == end {
        return format_timestamp(start);
    }

    format!("{} to {}", format_timestamp(start), format_timestamp(end))
}

fn status_label(status: &ComplianceStatus) -> &'static str {
    match status {
        ComplianceStatus::Compliant => "Compliant",
        ComplianceStatus::Partial => "Partial",
        ComplianceStatus::NonCompliant => "Non-Compliant",
    }
}

fn severity_label(severity: &GapSeverity) -> &'static str {
    match severity {
        GapSeverity::Low => "Low",
        GapSeverity::Medium => "Medium",
        GapSeverity::High => "High",
        GapSeverity::Critical => "Critical",
    }
}

fn integrity_label(status: &IntegrityState) -> &'static str {
    match status {
        IntegrityState::Verified => "Verified",
        IntegrityState::Warning => "Warning",
        IntegrityState::Broken => "Broken",
    }
}

fn wrap_for_width(value: &str, width: f32, font: FontFace, font_size: f32) -> Vec<String> {
    wrap_text(value, approx_chars_for_width(width, font, font_size))
}

fn approx_chars_for_width(width: f32, font: FontFace, font_size: f32) -> usize {
    ((width / (font_size * font.width_factor())).floor() as usize).max(1)
}

fn wrap_text(value: &str, width: usize) -> Vec<String> {
    let sanitized = sanitize_text(value);
    if sanitized.is_empty() {
        return vec![String::new()];
    }

    let mut lines = Vec::new();
    let mut current = String::new();

    for word in sanitized.split_whitespace() {
        if current.is_empty() {
            if word.len() <= width {
                current.push_str(word);
            } else {
                lines.extend(split_long_word(word, width));
            }
            continue;
        }

        if current.len() + 1 + word.len() <= width {
            current.push(' ');
            current.push_str(word);
            continue;
        }

        lines.push(current);
        current = String::new();

        if word.len() <= width {
            current.push_str(word);
        } else {
            lines.extend(split_long_word(word, width));
        }
    }

    if !current.is_empty() {
        lines.push(current);
    }

    if lines.is_empty() {
        lines.push(String::new());
    }

    lines
}

fn split_long_word(word: &str, width: usize) -> Vec<String> {
    word.chars()
        .collect::<Vec<_>>()
        .chunks(width)
        .map(|chunk| chunk.iter().collect::<String>())
        .collect()
}

fn sanitize_text(value: &str) -> String {
    value
        .chars()
        .map(|ch| {
            if ch.is_ascii_graphic() || ch == ' ' {
                ch
            } else if ch.is_ascii_whitespace() {
                ' '
            } else {
                '?'
            }
        })
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

fn append_fill_rect(content: &mut String, x: f32, top: f32, width: f32, height: f32, gray: f32) {
    let y = PAGE_HEIGHT - top - height;
    content.push_str(&format!(
        "{gray:.3} g\n{} {} {} {} re f\n",
        fmt_num(x),
        fmt_num(y),
        fmt_num(width),
        fmt_num(height)
    ));
}

fn append_stroke_rect(
    content: &mut String,
    x: f32,
    top: f32,
    width: f32,
    height: f32,
    gray: f32,
    line_width: f32,
) {
    let y = PAGE_HEIGHT - top - height;
    content.push_str(&format!(
        "{gray:.3} G\n{} w\n{} {} {} {} re S\n",
        fmt_num(line_width),
        fmt_num(x),
        fmt_num(y),
        fmt_num(width),
        fmt_num(height)
    ));
}

fn append_stroke_line(
    content: &mut String,
    x1: f32,
    top1: f32,
    x2: f32,
    top2: f32,
    gray: f32,
    line_width: f32,
) {
    let y1 = PAGE_HEIGHT - top1;
    let y2 = PAGE_HEIGHT - top2;
    content.push_str(&format!(
        "{gray:.3} G\n{} w\n{} {} m\n{} {} l\nS\n",
        fmt_num(line_width),
        fmt_num(x1),
        fmt_num(y1),
        fmt_num(x2),
        fmt_num(y2)
    ));
}

fn append_text(
    content: &mut String,
    x: f32,
    top: f32,
    font: FontFace,
    size: f32,
    gray: f32,
    text: &str,
) {
    let baseline_y = PAGE_HEIGHT - top - size;
    content.push_str(&format!(
        "BT\n{gray:.3} g\n/{} {} Tf\n1 0 0 1 {} {} Tm\n({}) Tj\nET\n",
        font.resource_name(),
        fmt_num(size),
        fmt_num(x),
        fmt_num(baseline_y),
        escape_text(text)
    ));
}

fn append_text_centered(
    content: &mut String,
    center_x: f32,
    top: f32,
    font: FontFace,
    size: f32,
    gray: f32,
    text: &str,
) {
    let width = estimate_text_width(text, font, size);
    append_text(content, center_x - width / 2.0, top, font, size, gray, text);
}

fn append_text_right_aligned(
    content: &mut String,
    right_x: f32,
    top: f32,
    font: FontFace,
    size: f32,
    gray: f32,
    text: &str,
) {
    let width = estimate_text_width(text, font, size);
    append_text(content, right_x - width, top, font, size, gray, text);
}

fn estimate_text_width(text: &str, font: FontFace, size: f32) -> f32 {
    sanitize_text(text).chars().count() as f32 * size * font.width_factor()
}

fn fmt_num(value: f32) -> String {
    format!("{value:.2}")
}

fn object(id: usize, body: String) -> String {
    format!("{id} 0 obj\n{body}\nendobj\n")
}

fn stream_object(id: usize, stream: &str) -> String {
    format!(
        "{id} 0 obj\n<< /Length {} >>\nstream\n{}\nendstream\nendobj\n",
        stream.len(),
        stream
    )
}

fn escape_text(value: &str) -> String {
    sanitize_text(value)
        .replace('\\', "\\\\")
        .replace('(', "\\(")
        .replace(')', "\\)")
}
